server:
  port: 8082
spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: false
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: movies-service
          uri: lb://MOVIES-SERVICE
          predicates:
            - Path=/movies/**
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**
  profiles:
    active: dev
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/DigitalMedia
        registration:
          api-gateway-service:
            provider: keycloak-provider
            clientId: api-gateway
            clientSecret: 3Y6w5YSPxEZ58SQAE71PbDPLkl3Ox1Xg
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
