server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZoeAgustinaTira/spring-cloud-config
          searchPaths: DigitalMediaConfig
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Config Microservice

